### ISSUE TITLE
Insufficient Access Rules: Stove_Canyon_20: Treasure G

### ISSUE THREAD

**Issue by LudwigVonKoopa87** [randomcodegen/wl_ap_tracker#1]
https://github.com/randomcodegen/wl_ap_tracker/blob/d97db00971f2a9a67dd3d16306ea1d11045c8fa4/locations/course_view/c20_blocks.json#L261

![wl_20](https://github.com/randomcodegen/wl_ap_tracker/assets/122737479/0a4de75c-a2e1-4133-8d58-2ab69339cb36)

You can't get through the first 2x4 level blockade with just a dragon hat unless you can duck because you can only clear 3 blocks wide with the flame, otherwise you need to lose your powerup to get through as small Wario and afterwards there is no more dragon hat to gain. Dash and jet are another possibilities.

Suggestion: `"access_rules": ["$can_climb, [$can_jet OR $can_dash OR [$can_dragon AND $can_duck]]"], `

**Comment by randomcodegen** [comment]
Fixed, thanks for the bug report.
