### ISSUE TITLE
Insufficient Access Rules: SS Tea Cup 26 - Treasure I

### ISSUE THREAD

**Issue by LudwigVonKoopa87** [randomcodegen/wl_ap_tracker#2]
https://github.com/randomcodegen/wl_ap_tracker/blob/d97db00971f2a9a67dd3d16306ea1d11045c8fa4/locations/course_view/c26_blocks.json#L255

![wl_26](https://github.com/randomcodegen/wl_ap_tracker/assets/122737479/d0012b4c-79e7-4042-97be-4d37826903ae)

You can't get through the 3x2 blockade with just a dragon hat unless you can duck because you can not clear the lower part of the door otherwise. Dash, Bull and Jet are another possibilities. 

With Bull you can do it because theres a Garlic and a Dragon powerup in the level. So if you entered the level with dragon, clear the upper half of the door, go back and get Bull with the Garlic, clear the lower door part with a groundpound, go back again and get the dragon, you can get the treasure this way.

Suggestion: `"access_rules": ["$can_climb, [$can_jet OR $can_bull OR $can_dash OR [$can_dragon AND $can_duck]]"], `

**Comment by bangerra88** [comment]
The room can be accessed like this:

![image](https://github.com/randomcodegen/wl_ap_tracker/assets/159690998/4814f008-9624-4cc6-8ece-1c5675011c1c)

**Comment by randomcodegen** [comment]
Fixed, thanks for the bug report.
