### ISSUE TITLE
Insufficient Access Rules: Parsley Woods 31_Rev - Treasure L

### ISSUE THREAD

**Issue by LudwigVonKoopa87** [randomcodegen/wl_ap_tracker#3]
https://github.com/randomcodegen/wl_ap_tracker/blob/d97db00971f2a9a67dd3d16306ea1d11045c8fa4/locations/course_view/c31rev_blocks.json#L299

![wl_31](https://github.com/randomcodegen/wl_ap_tracker/assets/122737479/4ab63a29-8dcb-4542-8fb5-60439589b715)

You can't get through the last block with just a dragon hat unless you can duck. Dash and Jet are another possibilities.

Suggestion: `"access_rules": ["pw_drained, $can_climb, [$can_jet OR $can_dash OR [$can_dragon AND $can_duck]]"]`

**Comment by randomcodegen** [comment]
Fixed, thanks for the bug report.
