### ISSUE TITLE
Insufficient Access Rules: Sherbet Land 15 - Block 4

### ISSUE THREAD

**Issue by LudwigVonKoopa87** [randomcodegen/wl_ap_tracker#4]
https://github.com/randomcodegen/wl_ap_tracker/blob/d97db00971f2a9a67dd3d16306ea1d11045c8fa4/locations/course_view/c15_blocks.json#L74

You need climb to get there.

Suggestion: `"access_rules": ["$can_climb,$can_dash","$can_climb,$can_dragon"], `

**Comment by randomcodegen** [comment]
Fixed in the new release. Thanks for the report.
