### ISSUE TITLE
Insufficient Access Rules: Stove Canyon 20 - Normal Exit

### ISSUE THREAD

**Issue by LudwigVonKoopa87** [randomcodegen/wl_ap_tracker#5]
https://github.com/randomcodegen/wl_ap_tracker/blob/d97db00971f2a9a67dd3d16306ea1d11045c8fa4/locations/course_view/c20_blocks.json#L240

The ladders can be traversed downwards by dashing against the adjacent walls. They can be traversed upwards by jet-dashing against the wall.

Suggestion: `"access_rules": ["$can_climb","can_jet"],`

**Comment by randomcodegen** [comment]
I feel like this would lead to confusion for the average player.
Will refrain from adding this for general ease of use.
