### ISSUE TITLE
Insufficient Access Rules: Stove Canyon 24 - Treasure H

### ISSUE THREAD

**Issue by LudwigVonKoopa87** [randomcodegen/wl_ap_tracker#6]
https://github.com/randomcodegen/wl_ap_tracker/blob/d97db00971f2a9a67dd3d16306ea1d11045c8fa4/locations/course_view/c24_blocks.json#L198

No need for climb. You can bring the key over to the beginning area with a jet flight, picking up the grounded key on the fly. Suggestion:

`"access_rules": ["$can_climb, $can_open_treasure", "can_jet"],`

**Comment by randomcodegen** [comment]
I feel like this would lead to confusion for the average player.
Will refrain from adding this for general ease of use.
